apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: view-app
          image: "{{ default "tooljet/" .Values.registry }}{{ default "tooljet-ce" .Values.repository }}:{{ default "v2.10.2" .Values.imageTag }}"
          imagePullPolicy: "{{ default "IfNotPresent" .Values.imagePullPolicy }}"
          args: 
            - npm
            - run
            - start:prod
          resources:
            {{- default dict .Values.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: {{ default "3000" .Values.port | int }}
          readinessProbe:
            httpGet:
              port: {{ default "3000" .Values.port | int }}
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cm
          env:
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ required "Postgres secret name is required" (.Values.postgres).secretName }}
                  key: POSTGRES_PASSWORD
            {{- if (.Values.postgrest).enabled }}
            - name: TOOLJET_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ required "Postgres secret name is required" (.Values.postgres).secretName }}
                  key: POSTGRES_PASSWORD
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "Redis secret name is required" (.Values.redis).secretName }}
                  key: REDIS_PASSWORD
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: lockbox_master_key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: secret_key_base
            {{- if (.Values.enterprise).enabled }}
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-license
                  key: license_key
            {{- end }}
