{{- if (ne .Values.createSecret false) }}
{{- $secret := printf "%s-secret" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-failed
  name: {{ $secret }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $lockboxKey := (get $secretData "lockbox_master_key") | default (randAlphaNum 64 | b64enc) }}
  {{- $secretKey := (get $secretData "secret_key_base") | default (randAlphaNum 128 | b64enc) }}
  lockbox_master_key: {{ $lockboxKey | quote }}
  secret_key_base: {{ $secretKey | quote }}
{{- end }}
