{{- $secret := printf "%s-secret" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $licenseKey := (get $secretData "license_key") | default "" }}
  {{- $lockboxKey := (get $secretData "lockbox_master_key") | default (randAlphaNum 64 | b64enc) }}
  {{- $secretKey := (get $secretData "secret_key_base") | default (randAlphaNum 128 | b64enc) }}
  license_key: {{ default $licenseKey ((.Values.enterprise).license | b64enc) | quote }}
  lockbox_master_key: {{ $lockboxKey | quote }}
  secret_key_base: {{ $secretKey | quote }}
