kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ default "5432" .Values.port | int }}
  selector:
    app: {{ .Release.Name }}
