# Recommended default FogLifter Traefik configurations

# FQDNs used to access FogLifter UI
hosts: []

# Namespace for FogLifter services
foglifterNamespace: foglifter

# Internal Traefik service FQDN
traefikService: traefik.traefik-system.svc.cluster.local

# TLS certificate configurations
certificate:
  # Use existing tls secret
  useExisting: false
  # Existing tls secret name
  name: ""

# FogLifter core app ingress configurations
core:
  # Core app service port
  port: 8080
  # Core app service name
  name: foglifter-core-svc
  # Core app service route path
  path: /api

# FogLifter main UI ingress configurations
mainUI:
  # main UI service port
  port: 80
  # main UI service name
  name: foglifter-main-ui-svc
  # main UI service route path
  path: /

# FogLifter apiservice ingress configurations
apiservice:
  # Apiservice service port
  port: 8080
  # Apiservice service name
  name: foglifter-apiservice-svc
  # Apiservice service route path
  path: /api/v1

# FogLifter auth service ingress configurations
auth:
  # auth service port
  port: 8080
  # auth service name
  name: foglifter-auth-svc
  # auth service route path
  path: /api/auth

# FogLifter UI client ingress configurations
client:
  # Client service port
  port: 8080
  # Client service name
  name: foglifter-client-svc
  # Client service route path
  path: /ui

# FogLifter module app ingress configurations
module:
  # Enable module app ingress
  enabled: true
  # Module app service port
  port: 8080
  # Module app service name
  name: foglifter-module-svc
  # Module app service route path
  path: /api/module

# FogLifter scheduler ingress configurations
scheduler:
  # Enable scheduler ingress
  enabled: true
  # Scheduler service port
  port: 8080
  # Scheduler service name
  name: foglifter-scheduler-svc
  # Scheduler service route path
  path: /scheduler

# Argo CD ingress configurations
argocd:
  # Enable Argo CD ingress
  enabled: true
  # Argo CD service port
  port: 80
  # Argo CD server service name
  name: foglifter-argocd-server
  # Argo CD server service namespace
  namespace: foglifter-argocd
  # Argo CD route path
  path: /argo-cd

# FogLifter View ingress configurations
view:
  # Enable View ingress
  enabled: true
  # View service port
  port: 3000
  # View app service name
  name: foglifter-view-svc
  # View app service namespace
  namespace: foglifter-view
  # View app route path
  path: /dashboard/

# FogLifter PGAdmin ingress configurations
pgadmin:
  # Enable PGAdmin ingress
  enabled: false
  # PGAdmin service port
  port: 5432
  # PGAdmin service name
  name: foglifter-postgres-pgadmin-svc
  # PGAdmin service namespace
  namespace: foglifter-postgres
  # PGAdmin route path
  path: /pgadmin

# MongoDB ingress configurations
mongo:
  # Enable Mongo ingress
  enabled: false
  # Mongo service port
  port: 27017
  # Mongo service name
  name: foglifter-mongo-svc
  # Mongo service namespace
  namespace: foglifter

# Postgres ingress configurations
postgres:
  # Enable Postgres ingress
  enabled: false
  # Postgres service port
  port: 5432
  # Postgres service name
  name: foglifter-postgres-svc
  # Postgres service namespace
  namespace: foglifter-postgres
