# Recommended default FogLifter Traefik configurations

# FQDN used to access FogLifter UI
host: ""

# Secondary FQDN or IP used to access FogLifter UI
secondaryHost: ""

# Namespace for FogLifter services
foglifterNamespace: foglifter

# # TLS certificate configurations
certificate:
  # Use existing tls secret
  useExisting: false
  # Existing tls secret name
  name: ""

# FogLifter core app ingress configurations
core:
  # Core app service port
  port: 8080
  # Core app service name
  name: foglifter-core-svc

# FogLifter main UI ingress configurations
mainUI:
  # main UI service port
  port: 80
  # main UI service name
  name: foglifter-main-ui-svc

# FogLifter apiservice ingress configurations
apiservice:
  # Apiservice service port
  port: 8080
  # Apiservice service name
  name: foglifter-apiservice-svc

# FogLifter auth service ingress configurations
auth:
  # auth service port
  port: 8080
  # auth service name
  name: foglifter-auth-svc

# FogLifter UI client ingress configurations
client:
  # Enable client ingress
  enabled: true
  # Client service port
  port: 8080
  # Client service name
  name: foglifter-client-svc

# FogLifter module app ingress configurations
module:
  # Enable module app ingress
  enabled: true
  # Module app service port
  port: 8080
  # Module app service name
  name: foglifter-module-svc

# FogLifter scheduler ingress configurations
scheduler:
  # Enable scheduler ingress
  enabled: true
  # Scheduler service port
  port: 8080
  # Scheduler service name
  name: foglifter-scheduler-svc

# Argo CD ingress configurations
argocd:
  # Enable Argo CD ingress
  enabled: true
  # Argo CD service port
  port: 80
  # Argo CD server service name
  name: foglifter-argocd-server
  # Argo CD server service namespace
  namespace: foglifter-argocd
  # Argo CD ingress prefix
  prefix: /argo-cd

# FogLifter View ingress configurations
view:
  # Enable View ingress
  enabled: true
  # View service port
  port: 3000
  # View app service name
  name: foglifter-view-svc
  # View app service namespace
  namespace: foglifter-view
  # View app ingress prefix
  prefix: /dashboard/

# FogLifter PGAdmin ingress configurations
pgadmin:
  # Enable PGAdmin ingress
  enabled: false
  # PGAdmin service port
  port: 5432
  # PGAdmin service name
  name: foglifter-postgres-pgadmin-svc
  # PGAdmin service namespace
  namespace: foglifter-postgres
  # PGAdmin ingress prefix
  prefix: /pgadmin

# MongoDB ingress configurations
mongo:
  # Enable Mongo ingress
  enabled: false
  # Mongo service port
  port: 27017
  # Mongo service name
  name: foglifter-mongo-svc
  # Mongo service namespace
  namespace: foglifter

# Postgres ingress configurations
postgres:
  # Enable Postgres ingress
  enabled: false
  # Postgres service port
  port: 5432
  # Postgres service name
  name: foglifter-postgres-svc
  # Postgres service namespace
  namespace: foglifter-postgres
