apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-auth
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- $host := "" }}
    {{- if .Values.host }}
      {{- if .Values.secondaryHost }}
        {{- $host = (printf "(Host(`%s`) || Host(`%s`)) && " .Values.host .Values.secondaryHost) }}
      {{- else }}
        {{- $host = (printf "Host(`%s`) && " .Values.host) }}
      {{- end }}
    {{- end }}
    - match: {{ $host }}PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: {{ default "foglifter-auth-svc" (.Values.auth).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.auth).port | int }}
  {{- if (eq (.Values.certificate).useExisting true ) }}
  tls:
    secretName: {{ default "foglifter-traefik-cert" (.Values.certificate).name }}
  {{- end }}
