apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-module
spec:
  entryPoints:
    - web
    - websecure
  {{- $host := "" }}
  {{- if .Values.host }}
    {{- $host = default "" (printf "Host(`%s`) && " .Values.host) }}
  {{- else }}
    {{- $host = "" }}
  {{- end }}
  routes:
    - match: {{ $host }}PathPrefix(`{{ default "/api/module" (.Values.module).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-module-svc" (.Values.module).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.module).port | int }}
  {{- if (eq (.Values.certificate).useExisting true ) }}
  tls:
    secretName: {{ default "foglifter-traefik-cert" (.Values.certificate).name }}
  {{- end }}
