{{- if (ne (.Values.pgadmin).enabled false) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{ include "traefik.hosts" .Values }}{{ include "traefik.path" .Values.pgadmin }}
      kind: Rule
      services:
        - name: {{ default "foglifter-pgadmin-svc" (.Values.pgadmin).name }}
          namespace: {{ default "foglifter-postgres" (.Values.pgadmin).namespace }}
          port: {{ default "5432" (.Values.pgadmin).port | int }}
  {{- if (eq (.Values.certificate).useExisting true ) }}
  tls:
    secretName: {{ default "foglifter-traefik-cert" (.Values.certificate).name }}
  {{- end }}
{{- end }}
