{{- if (ne (.Values.pgadmin).enabled false) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- $host := "" }}
    {{- if .Values.host }}
      {{- if .Values.secondaryHost }}
        {{- $host = (printf "(Host(`%s`) || Host(`%s`)) && " .Values.host .Values.secondaryHost) }}
      {{- else }}
        {{- $host = (printf "Host(`%s`) && " .Values.host) }}
      {{- end }}
    {{- end }}
    - match: {{ $host }}PathPrefix(`{{ default "/pgadmin" (.Values.pgadmin).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-pgadmin-svc" (.Values.pgadmin).name }}
          namespace: {{ default "foglifter-postgres" (.Values.pgadmin).namespace }}
          port: {{ default "5432" (.Values.pgadmin).port | int }}
  {{- if (eq (.Values.certificate).useExisting true ) }}
  tls:
    secretName: {{ default "foglifter-traefik-cert" (.Values.certificate).name }}
  {{- end }}
{{- end }}
