kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-conf-cm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-failed
  labels:
    app: {{ .Release.Name }}
data:
  mongod.conf: |
    # mongod.conf
    # http://docs.mongodb.org/manual/reference/configuration-options/
    storage:
      dbPath: {{ default "/data/db" .Values.dbPath }}
      journal:
        enabled: true
      {{- if .Values.wiredTigerConfig }}
      engine: wiredTiger
      wiredTiger:
       {{- default dict .Values.wiredTigerConfig | toYaml | nindent 8 }}
      {{- end }}
    net:
      port: {{ default "27017" .Values.port | int }}
      bindIp: 0.0.0.0
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    {{- if (eq (.Values.replication).enabled true) }}
    replication:
      replSetName: {{ default "foglifterRS" (.Values.replication).name }}
    {{- end }}
    security:
      authorization: enabled
      {{- if (eq (.Values.replication).enabled true) }}
      keyFile: {{ default "/data/db" .Values.dbPath }}/mongod.key
      {{- end }}
