kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-init-cm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-failed
  labels:
    app: {{ .Release.Name }}
data:
  {{- $path := default "/data/db" .Values.dbPath }}
  {{- $port := default "27017" .Values.port | int }}
  mongo-init.sh: |
    #!/bin/sh
    {{- if (eq (.Values.replication).enabled true) }}
    if [ ! -f "{{ $path }}/mongod.key" ]; then
      echo "$MONGO_REPLICA_SET_KEY" > {{ $path }}/mongod.key
      chmod 0400 {{ $path }}/mongod.key
      chown 999:999 {{ $path }}/mongod.key
    fi
    {{- end }}
    if [ ! -f "{{ $path }}/mongo-init.txt" ]; then
      if [ "$HOSTNAME" = "{{ .Release.Name }}-0" ]; then
        mongo admin -eval 'db.auth("root", "'"$MONGO_INITDB_ROOT_PASSWORD"'"); db.createUser({user:"'"$MONGO_APP_USER"'", pwd:"'"$MONGO_APP_PSWD"'", roles: [{role:"read", db:"admin"}, {role:"dbOwner", db:"'"$MONGO_INITDB_DATABASE"'"}]});'
      fi
      echo "mongo-init.sh ran" > {{ $path }}/mongo-init.txt
    fi
