{{- if (eq .Values.createSecret true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- $appPswd := randAlphaNum 64 }}
  MONGO_APP_PSWD: {{ $appPswd | b64enc }}
  MONGO_ROOT_PSWD: {{ randAlphaNum 64 | b64enc }}
  {{- $dbName := default "foglifterDB" .Values.dbName }}
  {{- $port := default "27017" .Values.port | toString }}
  {{- if (eq (.Values.replication).enabled true) }}
  {{- $rsName := default "foglifterRS" (.Values.replication).name }}
  MONGO_URI: {{ printf "mongodb://flUser:%s@mongo-0.mongo-svc:%s,mongo-1.mongo-svc:%s,mongo-2.mongo-svc:%s/%s?replicaSet=%s&authSource=admin&ssl=false" $appPswd $port $port $port $dbName $rsName | b64enc }}
  {{- else }}
  MONGO_URI: {{ printf "mongodb://flUser:%s@mongo-0.mongo-svc:%s/%s?&authSource=admin&ssl=false" $appPswd $port $dbName | b64enc }}
  {{- end }}
{{- end }}
