{{- $secret := printf "%s-postgres-secret" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pswd := (get $secretData "POSTGRES_PASSWORD") | default (randAlphaNum 64 | b64enc) }}
  POSTGRES_PASSWORD: {{ $pswd | quote }}
