kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-svc
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ default "5432" (.Values.postgres).port | int }}
  selector:
    app: {{ .Release.Name }}-postgres
