kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ default "1" (.Values.auth).replicas | int }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-auth
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: auth-app
          {{- $imageTagDelimiter := ":" }}
          {{- if (hasPrefix "sha256:" (.Values.auth).tag) }}
            {{- $imageTagDelimiter = "@" }}
          {{- end }}
          image: "{{ default "ghcr.io/vso-inc/" .Values.registry }}{{ default "foglifter-auth-service" (.Values.auth).repository }}{{ $imageTagDelimiter }}{{ default "latest" (.Values.auth).tag }}"
          imagePullPolicy: "{{ default "Always" .Values.imagePullPolicy }}"
          args:
            - node
            - dist/main.js
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cm
            {{- if and (ne (.Values.secret).create false) (.Values.secret).data }}
            - secretRef:
                name: {{ .Release.Name }}-secret
            {{- end }}
            {{- if .Values.apiPasswordSecret }}
            - secretRef:
                name: {{ .Values.apiPasswordSecret }}
            {{- end }}
          {{- $port := default "8080" (.Values.auth).port | int }}
          env:
            {{- if or (.Values.apiservice).trustToken (.Values.auth).trustToken }}
            - name: TRUST_TOKEN_HASH_KEY
              value: "{{ (.Values.auth).trustToken | default (.Values.apiservice).trustToken }}"
            {{- end }}
            - name: PORT
              value: "{{ $port }}"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  {{- $mongoSecret := "" }}
                  {{- if .Values.mongoSecret }}
                    {{- $mongoSecret = .Values.mongoSecret }}
                  {{- else }}
                    {{- range $i, $secret := (lookup "v1" "Secret" .Release.Namespace "").items }}
                      {{- if (get (get $secret "data" | default dict) "MONGO_URI") }}
                        {{- $mongoSecret = $secret.metadata.name }}
                      {{- end }}
                    {{- end }}
                    {{- if not $mongoSecret }}
                      {{- $mongoSecret = "foglifter-mongo-secret" }}
                    {{- end }}
                  {{- end }}
                  name: {{ $mongoSecret }}
                  key: MONGO_URI
            {{- if (.Values.auth).env }}
            {{- range $key, $val := .Values.auth.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- if (.Values.auth).secretRef }}
            {{- with .Values.auth.secretRef }}
            {{- range $key, $val := . }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.name }}
                  key: {{ $val.key }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ $port }}
          resources:
            {{- default dict (.Values.auth).resources | toYaml | nindent 12 }}
      {{- if (ne (.Values.priorityClass).create false) }}
      priorityClassName: {{ .Release.Name }}
      {{- end }}
