
{{- if (ne (.Values.pgadmin).createSecret false) }}
{{- $secret := printf "%s-pgadmin-secret" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    helm.sh/hook-delete-policy: hook-failed
  name: {{ $secret }}
  labels:
    app: {{ .Release.Name }}-pgadmin
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pswd := (get $secretData "PGADMIN_DEFAULT_PASSWORD") | default (randAlphaNum 64 | b64enc) }}
  PGADMIN_DEFAULT_PASSWORD: {{ $pswd | quote }}
{{- end }}
