{{- if (.Values.pgadmin).enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pgadmin-svc
  labels:
    app: {{ .Release.Name }}-pgadmin
spec:
  type: ClusterIP
  ports:
    - port: {{ default "5432" .Values.port | int }}
  selector:
    app: {{ .Release.Name }}-pgadmin
{{- end }}
