{{- with (.Values.compliance).db }}
{{- if and .enabled (.secret).create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-compliance-db-secret
  labels:
    app: {{ $.Release.Name }}-compliance
type: Opaque
stringData:
  DB_PASSWORD: {{ default ((.mssql).auth).password (.secret).password }}
  DB_URL: {{ (.secret).url }}
  JWT_SECRET_KEY: {{ (.secret).jwt }}
{{- end }}
{{- end }}
