---
apiVersion: v2
name: foglifter
description: Helm chart for FogLifter® installation

type: application

version: 1.1.0

appVersion: "4.6"
dependencies:
  - name: mongodb-kubernetes
    repository: https://mongodb.github.io/helm-charts
    version: 1.8.0
    condition: mongodb-kubernetes.enabled
  - name: mssql
    repository: oci://registry.gitlab.com/xrow-public/helm-mssql/charts
    version: 1.6.1
    condition: mssql.enabled
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 39.0.7
    condition: traefik.enabled
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.27.1
    condition: cloudnative-pg.enabled
  - name: cluster
    repository: https://cloudnative-pg.github.io/charts
    version: 0.6.0
    condition: cluster.enabled
