{{- if (ne (.Values.client).enabled false) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-client-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  {{- $port := default "8080" (.Values.client).port | int }}
  ports:
  - port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: {{ .Release.Name }}-client
{{- end }}
