{{- include "foglifter.deployment" (dict
    "root" . "name" "routing" "svc" .Values.routing "container" "routing"
    "port" (.Values.routing.port | int) "portEnv" true "mongoUri" true "startupProbe" true) }}
