apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ default "foglifter-core-svc" (.Values.core).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.core).port | int }}
    - match: PathPrefix(`{{ default "/api/auth" (.Values.apiservice).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-apiservice-svc" (.Values.apiservice).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.apiservice).port | int }}
    - match: PathPrefix(`{{ default "/api/module" (.Values.module).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-module-svc" (.Values.module).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.module).port | int }}
    {{- if (ne (.Values.argocd).enabled false) }}
    - match: PathPrefix(`{{ default "/argo-cd" (.Values.argocd).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-argocd-server" (.Values.argocd).name }}
          namespace: {{ default "foglifter-argocd" (.Values.argocd).namespace }}
          port: {{ default "80" (.Values.argocd).port | int }}
    {{- end }}
    {{- if (ne (.Values.view).enabled false) }}
    - match: PathPrefix(`{{ default "/dashboard" (.Values.view).prefix }}`)
      kind: Rule
      services:
        - name: {{ default "foglifter-view-svc" (.Values.view).name }}
          namespace: {{ default "foglifter-view" (.Values.view).namespace }}
          port: {{ default "3000" (.Values.view).port | int }}
    {{- end }}
  tls:
    secretName: foglifter-traefik-cert
