{{- if (ne (.Values.mongo).enabled false) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  entryPoints:
    - mongo
  routes:
    {{- $host := "" }}
    {{- if .Values.host }}
      {{- if .Values.secondaryHost }}
        {{- $host = (printf "HostSNI(`%s`) || HostSNI(`%s`)" .Values.host .Values.secondaryHost) }}
      {{- else }}
        {{- $host = (printf "HostSNI(`%s`)" .Values.host) }}
      {{- end }}
    {{- else }}
      {{- $host = "HostSNI(`*`)" }}
    {{- end }}
    - match: {{ $host }}
      services:
        - name: {{ default "foglifter-mongo-svc" (.Values.mongo).name }}
          namespace: {{ default "foglifter" (.Values.mongo).namespace }}
          port: {{ default "27017" (.Values.mongo).port | int }}
{{- end }}