{{- if (ne (.Values.postgres).enabled false) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ default "foglifter-postgres-svc" (.Values.postgres).name }}
          namespace: {{ default "foglifter-postgres" (.Values.postgres).namespace }}
          port: {{ default "5432" (.Values.postgres).port | int }}
{{- end }}