{{- if (eq ((.Values.mongo).application).install true) }}
{{- $values := (omit .Values.mongo "application") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default "foglifter-mongo" ((.Values.mongo).application).name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/MONGO_APP_PSWD
        - /data/MONGO_ROOT_PSWD
        - /data/MONGO_URI
        - /data/MONGO_REPLICA_SET_KEY
  project: {{ default "foglifter" ((.Values.mongo).application).project }}
  source:
    chart: foglifter-mongo
    repoURL: https://vso-inc.github.io/foglifter-helm
    targetRevision: {{ ((.Values.mongo).application).version | semver }}
    helm:
      values: |
        {{- default dict $values | toYaml | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    {{- $foglifterNamespace := (default "foglifter" ((.Values.foglifter).application).namespace ) }}
    namespace: {{ default $foglifterNamespace ((.Values.mongo).application).namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
