{{- if and (.Values.postgrest).enabled (.Values.postgrest).secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgrest.secret.name }}
type: Opaque
stringData:
  PGRST_DB_URI: {{ .Values.postgrest.secret.dbUri | quote }}
  PGRST_JWT_SECRET: {{ default (randAlphaNum 64) .Values.postgrest.secret.jwt | quote }}
{{- end }}