{{- if (.Values.postgrest).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgrest-svc
  labels:
    app: {{ .Release.Name }}-postgrest
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.postgrest.port }}
      targetPort: {{ .Values.postgrest.port }}
  selector:
    app: {{ .Release.Name }}-postgrest
{{- end }}