kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-scheduler-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  {{- $port := default "8011" (.Values.scheduler).port | int }}
  ports:
  - port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: {{ .Release.Name }}-scheduler
