{{- if and .Values.gatewayAPI.enabled .Values.gatewayAPI.httpRoute.enabled }}
{{- if .Values.gatewayAPI.gateway.listeners.http.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gatewayAPI.httpRoute.name }}-http
  namespace: {{ default .Release.Namespace .Values.gatewayAPI.httpRoute.namespace }}
  {{- with .Values.gatewayAPI.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayAPI.gateway.name }}
      sectionName: http
      namespace: {{ default .Release.Namespace .Values.gatewayAPI.gateway.namespace }}
  {{- if or .Values.domain .Values.gatewayAPI.httpRoute.hostnames }}
  hostnames:
    {{- if .Values.domain }}
    - {{ .Values.domain }}
    {{- end }}
    {{- with .Values.gatewayAPI.httpRoute.hostnames }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- include "foglifter.httpRouteRules" (dict "root" . "listener" "http" "httpsEnabled" .Values.gatewayAPI.gateway.listeners.https.enabled "httpsRedirect" .Values.gatewayAPI.httpRoute.httpsRedirect) | nindent 2 }}
{{- end }}
{{- end }}
