{{- if and .Values.gatewayAPI.enabled .Values.gatewayAPI.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gatewayAPI.httpRoute.name }}-internal
  namespace: {{ default .Release.Namespace .Values.gatewayAPI.httpRoute.namespace }}
  {{- with .Values.gatewayAPI.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayAPI.gateway.name }}
      sectionName: http
      namespace: {{ default .Release.Namespace .Values.gatewayAPI.gateway.namespace }}
  hostnames:
    - {{ .Values.serviceMesh.domain }}
  {{- include "foglifter.httpRouteRules" (dict "root" . "listener" "internal") | nindent 2 }}
{{- end }}
