{{- if .Values.createPostgresRoleSecrets }}
{{- range ((.Values.cluster).cluster).roles }}
{{- if and .passwordSecret .passwordSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecret.name }}
  labels:
    app: {{ $.Release.Name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .name | quote }}
  password: {{ randAlphaNum 32 | quote }}
{{- end }}
{{- end }}
{{- end }}
