{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
value: {{ .Values.priorityClass.value | int }}
globalDefault: false
description: "This priority class is reserved for FogLifter pods."
{{- end }}