{{- if and (ne (.Values.secret).create false) (.Values.secret).data }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- (.Values.secret).data | toYaml | nindent 2 }}
{{- end }}
