apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}
{{- if .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{ default "foglifter-pullsecret" .Values.imagePullSecret }}
{{- end }}
