{{- if (ne (.Values.cm).create false) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cm
  labels:
    app: {{ .Release.Name }}
data:
  {{- if not ((.Values.cm).data).API_SERVICE_URI }}
  API_SERVICE_URI: {{ printf "http://%s-apiservice-svc:%s/api/v1" .Release.Name (default "8080" (.Values.apiservice).port | toString) | quote }}
  {{- end }}
  {{- if (.Values.cm).data }}
  {{- (.Values.cm).data | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
