# Recommended default FogLifter Istio configurations

# Allowed hosts list
hosts:
  - "*"

# Argo CD ingress configurations
argocd:
  # Enable Argo CD ingress
  enabled: true
  # Argo CD ingress port
  port: 80
  # Internal FQDN of Argo CD server service
  # e.g. foglifter-argocd-server.foglifter-argocd.svc.cluster.local
  fqdn: ""
  # Argo CD ingress prefix
  prefix: /argo-cd

# FogLifter apiservice ingress configurations
apiservice:
  # Apiservice ingress port
  port: 8080
  # Internal FQDN of apiservice service
  # e.g. foglifter-apiservice-svc.foglifter.svc.cluster.local
  fqdn: ""
  # Apiservice ingress prefix
  prefix: /api/auth

# FogLifter core app ingress configurations
core:
  # Core app ingress port
  port: 8080
  # Internal FQDN of core app service
  # e.g. foglifter-core-svc.foglifter.svc.cluster.local
  fqdn: ""

# FogLifter module app ingress configurations
module:
  # Module app ingress port
  port: 8080
  # Internal FQDN of module app service
  # e.g. foglifter-module-svc.foglifter.svc.cluster.local
  fqdn: ""
  # Module app ingress prefix
  prefix: /api/module

# FogLifter View ingress configurations
view:
  # Enable View ingress
  enabled: true
  # View ingress port
  port: 3000
  # # Internal FQDN of View service
  # e.g. foglifter-view-svc.foglifter-view.svc.cluster.local
  fqdn: ""
  # View app ingress prefix
  prefix: /dashboard

# MongoDB ingress configurations
mongo:
  # Enable Mongo ingress
  enabled: true
  # Mongo ingress port
  port: 27017
  # # Internal FQDN of View service
  # e.g. foglifter-mongo-svc.foglifter-mongo.svc.cluster.local
  fqdn: ""

http:
  # Enable HTTP
  enabled: true
  # Istio HTTP ingress port
  port: 80

# Istio HTTPS ingress port
httpsPort: 443
# Istio status-port
statusPort: 15021
