{{- if .Values.client.enabled }}
{{- include "foglifter.deployment" (dict
    "root" . "name" "client" "svc" .Values.client "container" "client"
    "port" 80 "portEnv" false "mongoUri" false "startupProbe" true) }}
{{- end }}
