{{- with (.Values.compliance).ems }}
{{- if and .enabled (.secret).create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-compliance-ems-secret
  labels:
    app: {{ $.Release.Name }}-compliance
type: Opaque
stringData:
  BIGFIX_API_TOKEN: {{ (.secret).token }}
  BIGFIX_PASSWORD: {{ (.secret).password }}
  JWT_SECRET: {{ (.secret).jwt }}
{{- end }}
{{- end }}
