kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongo-conf-cm
  labels:
    app: {{ .Release.Name }}-mongo
data:
  mongod.conf: |
    # mongod.conf
    # http://docs.mongodb.org/manual/reference/configuration-options/
    storage:
      dbPath: {{ default "/data/db" (.Values.mongo).dbPath }}
      journal:
        enabled: true
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: {{ default "27017" (.Values.mongo).port | int }}
      bindIp: 0.0.0.0
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    {{- if (eq ((.Values.mongo).replication).enabled true) }}
    replication:
      replSetName: {{ default "foglifterRS" ((.Values.mongo).replication).name }}
    {{- end }}
    security:
      authorization: enabled
      {{- if (eq ((.Values.mongo).replication).enabled true) }}
      keyFile: {{ default "/data/key" ((.Values.mongo).replication).keyPath }}/mongod.key
      {{- end }}
