kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  serviceName: {{ .Release.Name }}-mongo-svc
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      serviceAccountName: {{ .Release.Name }}-mongo-sa
      terminationGracePeriodSeconds: 10
      {{- $dbPath := default "/data/db" (.Values.mongo).dbPath }}
      {{- $configPath := default "/data/conf" (.Values.mongo).configPath }}
      containers:
        - name: mongo
          args:
            - --config
            - "{{ $configPath }}/mongod.conf"
          image: "{{ default "" (.Values.mongo).registry }}{{ default "mongo" (.Values.mongo).repository }}:{{ default "5.0.6" (.Values.mongo).imageTag }}"
          imagePullPolicy: "{{ default "Always" (.Values.mongo).imagePullPolicy }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secret
                  key: MONGO_ROOT_PSWD
            - name: MONGO_INITDB_DATABASE
              value: "{{ default "foglifterDB" (.Values.mongo).dbName }}"
            - name: MONGO_APP_USER
              value: flUser
            - name: MONGO_APP_PSWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secret
                  key: MONGO_APP_PSWD
          ports:
            - containerPort: {{ default "27017" (.Values.mongo).port | int }}
          resources:
            {{- toYaml (.Values.mongo).resources | nindent 12 }}
          volumeMounts:
            - name: mongo-pvc
              mountPath: "{{ $dbPath }}"
            - name: mongo-init
              mountPath: "/docker-entrypoint-initdb.d"
            - name: mongod-conf
              mountPath: "{{ $configPath }}"
      volumes:
        - name: mongo-init
          configMap:
            name: {{ .Release.Name }}-mongo-init-cm
            defaultMode: 0777
            items:
              - key: mongo-init.sh
                path: mongo-init.sh
                mode: 0777
        - name: mongod-conf
          configMap:
            name: {{ .Release.Name }}-mongo-conf-cm
            defaultMode: 0777
            items:
              - key: mongod.conf
                path: mongod.conf
                mode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-mongo-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ default "10Gi" (.Values.mongo).storage }}"
