{{- if (ne (.Values.redis).deploy false) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-cm
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
{{- end }}
