kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  hosts:
    {{- default (list "*") .Values.hosts | toYaml | nindent 4 }}
  gateways:
    - {{ .Release.Name }}
  http:
    {{- if (ne (.Values.argocd).enabled false) }}
    - match:
        - uri:
            prefix: {{ default "/argo-cd" (.Values.argocd).prefix }}
      route:
        - destination:
            host: {{ default "" (.Values.argocd).fqdn }}
            port:
              number: {{ default "80" (.Values.argocd).port | int }}
    {{- end }}
    - match:
        - uri:
            prefix: {{ default "/api/auth" (.Values.apiservice).prefix }}
      route:
        - destination:
            host: {{ default "" (.Values.apiservice).fqdn }}
            port:
              number: {{ default "8080" (.Values.apiservice).port | int }}
    - route:
        - destination:
            host: {{ default "" (.Values.core).fqdn }}
            port:
              number: {{ default "8080" (.Values.core).port | int }}
    - match:
        - uri:
            prefix: {{ default "/api/module" (.Values.module).prefix }}
      route:
        - destination:
            host: {{ default "" (.Values.module).fqdn }}
            port:
              number: {{ default "8080" (.Values.module).port | int }}
    {{- if (ne (.Values.view).enabled false) }}
    - match:
        - uri:
            prefix: {{ default "/dashboard" (.Values.view).prefix }}
      route:
        - destination:
            host: {{ default "" (.Values.view).fqdn }}
            port:
              number: {{ default "3000" (.Values.view).port | int }}
    {{- end }}
  {{- if (ne (.Values.mongo).enabled false) }}
  tcp:
    - match:
        - port: {{ default "27017" (.Values.mongo).port | int }}
      route:
        - destination:
            host: {{ default "" (.Values.mongo).fqdn }}
            port:
              number: {{ default "27017" (.Values.mongo).port | int }}
  {{- end }}
