{{- if .Values.notification.enabled }}
{{- include "foglifter.deployment" (dict
    "root" . "name" "notification" "svc" .Values.notification "container" "notification"
    "port" "" "portEnv" false "mongoUri" false "probeRaw" true "startupProbe" false) }}
{{- end }}
