{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "foglifter-headlamp.fullname" . }}-viewer
  labels:
    {{- include "foglifter-headlamp.labels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- else }}
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get"]
  {{- end }}
{{- end }}
