{{- if .Values.serviceAccount.tokenSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headlamp.serviceAccount.name | required ".Values.headlamp.serviceAccount.name is required" }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.headlamp.serviceAccount.name }}
  labels:
    {{- include "foglifter-headlamp.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
