kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-core-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  {{- $port := default "8080" (.Values.core).port | int }}
  ports:
  - port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: {{ .Release.Name }}-core
