{{- if (eq ((.Values.traefik).application).install true) }}
{{- $values := (omit .Values.traefik "application") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default "foglifter-traefik" ((.Values.traefik).application).name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default "traefik" ((.Values.traefik).application).project }}
  source:
    chart: foglifter-traefik
    repoURL: https://vso-inc.github.io/foglifter-helm
    targetRevision: {{ default "0.1.1" ((.Values.traefik).application).version | semver }}
    helm:
      values: |
        {{- default dict $values | toYaml | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default "traefik-system" ((.Values.traefik).application).namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
