apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default "traefik" ((.Values.traefik).application).project }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Traefik ingress
  sourceRepos:
    - '*'
  destinations:
    - namespace: {{ default "traefik-system" ((.Values.traefik).application).namespace }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: policy
      kind: PodSecurityPolicy
    - group: gateway.networking.k8s.io
      kind: GatewayClass
    - group: networking.k8s.io
      kind: IngressClass
