name: Helm Install & Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-install-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: docker.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        id: install
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          rm -rf get_helm.sh

      - name: Create K3s cluster
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
          echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

      - name: Create FogLifter pullsecret
        run: |
          kubectl create ns foglifter
          kubectl -n foglifter create secret docker-registry foglifter-pullsecret \
          --docker-server "${{ env.IMAGE_REGISTRY }}" \
          --docker-username "${{ secrets.IMAGE_REGISTRY_USERNAME }}" \
          --docker-password "${{ secrets.IMAGE_REGISTRY_PASSWORD }}"

      # - name: Install and Test foglifter-mongo chart
      #   env:
      #     CHART_DIR: charts/foglifter-mongo
      #   run: >
      #     helm install --debug --wait foglifter-mongo $CHART_DIR
      #     --namespace foglifter
      #     --timeout 120s
      #     --values $CHART_DIR/values.yaml
      #     --values $CHART_DIR/ci/values.yaml

      # - name: Install and Test foglifter chart
      #   env:
      #     CHART_DIR: charts/foglifter
      #   run: >
      #     helm install --debug --wait foglifter $CHART_DIR
      #     --namespace foglifter
      #     --timeout 120s
      #     --values $CHART_DIR/values.yaml
      #     --values $CHART_DIR/ci/values.yaml

      - name: Install and Test foglifter-view chart
        env:
          CHART_DIR: charts/foglifter-view
        run: >
          helm install --debug foglifter-view $CHART_DIR
          --namespace foglifter
          --values $CHART_DIR/values.yaml
          --values $CHART_DIR/ci/values.yaml

      - name: Debug foglifter-view
        run: |
          set +e
          while true; do
            kubectl -n foglifter logs -f -l app=foglifter-view
            sleep 1
          done

      - name: Clean up releases
        run: |
          for rel in `helm ls -n foglifter -q`; do
            helm uninstall --debug --wait -n foglifter $rel
          done
