{{- if (ne (.Values.argocd).enabled false) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-argocd-http
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "traefik.hosts" .Values }}{{ include "traefik.path" .Values.argocd }}
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ default "foglifter-argocd-server" (.Values.argocd).name }}
          namespace: {{ default "foglifter-argocd" (.Values.argocd).namespace }}
          port: {{ default "80" (.Values.argocd).port | int }}
    {{- if .Values.traefikService }}
    - match: {{ printf "Host(`%s`) && " .Values.traefikService }}{{ include "traefik.path" .Values.argocd }}
      kind: Rule
      services:
        - name: {{ default "foglifter-argocd-server" (.Values.argocd).name }}
          namespace: {{ default "foglifter-argocd" (.Values.argocd).namespace }}
          port: {{ default "80" (.Values.argocd).port | int }}
    {{- end }}
{{- end }}
