{{- if (eq ((.Values.view).application).install true) }}
{{- $values := (omit .Values.view "application") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default "foglifter-view" ((.Values.view).application).name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default "view" ((.Values.view).application).project }}
  source:
    chart: foglifter-view
    repoURL: https://github.com/vso-inc/foglifter-helm/tree/develop/charts
    targetRevision: {{ default "0.1.0" ((.Values.view).application).version | semver }}
    helm:
      values: |
        {{- default dict $values | toYaml | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default "foglifter-view" ((.Values.view).application).namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
